name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm  # Change to npm for caching npm dependencies

      - name: Install dependencies
        run: npm ci  # Use npm ci for installing dependencies based on package-lock.json
      - name: Build website
        run: npm run build  # Use your npm build script here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
          user_name: Bal Narendra Sapa
          user_email: bnsapa2000@gmail.com
